apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: rogercodeprojects/${{ values.name }}
spec:
  type: other
  lifecycle: unknown
  owner: developer
  providesApis:
    - ${{ values.name }}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}-api
  description: API definition for ${{ values.name }}
spec:
  type: openapi
  lifecycle: production
  owner: developer
  definition: file:./openapi.json
