apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: writmi
  description: Writmi environment
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - writmi
spec:
  owner: developer
  domain: artists
