apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: artist-engagement-portal
  description: Everything related to artists
  annotations:
    backstage.io/techdocs-ref: dir:./docs/mkdocs.yml
  tags:
    - portal
spec:
  owner: team-a
  domain: artists
